#!/usr/bin/env bash
# A script to install nginx on a web server

sudo apt-get -y update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
sudo echo 'Hello World' > /var/www/html/index.nginx_debian.html
