#!/usr/bin/env bash
# A script to install and configure nginx on a web server

# Update the package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get install nginx -y

# Enable UFW if not already enabled
sudo ufw enable

# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Restart the Nginx service using service command
sudo service nginx restart

# Give the appropraite permissions to the user
chown -R $USER:$USER /var/www/html /var/www/joetalkscode.tech/html
chmod -R 755 /var/www

# Create a simple HTML file with "Hello World!" to verify the installation
echo -e 'Hello World!' > /var/www/html/index.nginx-debian.html

# Ensure Nginx is listening on port 80 (default configuration)
# sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Reload the ufw service
sudo ufw reload

# Restart the Nginx service using service command
sudo service nginx restart

# Print the status of Nginx to ensure it is running and listening on port 80
# sudo service nginx status

