#!/usr/bin/env bash
# A fizzbuzz printing script

count=100
i=1

while [ "$i" -le "$count" ];
do
	if [ "$((i % 15))" == 0 ]
	then
		echo "FizzBuzz"
	elif [ "$((i % 5))" -eq 0 ]
	then
		echo "Buzz"
	elif [ "$((i % 3))" -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$i"
	fi
	((i++))
done
