#!/usr/bin/env bash
# A script to print a clock

hour=12
minute=59

i=1
j=0

while [[ j -le hour ]];
do
	echo "Hour: $j"
	while [[ i -le minute ]];
	do
		echo "$i"
		(( i++ ))
	done
	(( i = 1 ))
	(( j++ ))
done
